# Generated by Django 5.0 on 2023-12-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
